/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { LifeContract } from "./LifeContract";
export * as factories from "./factories";
export { LifeContract__factory } from "./factories/LifeContract__factory";
