/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface LifeContractInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addHeir"
      | "executeEstate"
      | "executed"
      | "getDaysElapsed"
      | "getHeir"
      | "getHeirsCount"
      | "getStatus"
      | "getThresholdDays"
      | "isHeir"
      | "isInactive"
      | "lastPing"
      | "owner"
      | "ping"
      | "registerHeir"
      | "setThreshold"
      | "threshold"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EstateExecuted"
      | "HeartbeatReceived"
      | "HeirAdded"
      | "HeirRegistered"
      | "ThresholdUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addHeir",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executeEstate",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "executed", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getDaysElapsed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getHeir",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getHeirsCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getStatus", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getThresholdDays",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "isHeir", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "isInactive",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "lastPing", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "ping", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerHeir",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setThreshold",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "threshold", values?: undefined): string;

  decodeFunctionResult(functionFragment: "addHeir", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeEstate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "executed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDaysElapsed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getHeir", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getHeirsCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getStatus", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getThresholdDays",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isHeir", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isInactive", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lastPing", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ping", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerHeir",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "threshold", data: BytesLike): Result;
}

export namespace EstateExecutedEvent {
  export type InputTuple = [
    timestamp: BigNumberish,
    totalValue: BigNumberish,
    heirCount: BigNumberish
  ];
  export type OutputTuple = [
    timestamp: bigint,
    totalValue: bigint,
    heirCount: bigint
  ];
  export interface OutputObject {
    timestamp: bigint;
    totalValue: bigint;
    heirCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HeartbeatReceivedEvent {
  export type InputTuple = [timestamp: BigNumberish, caller: AddressLike];
  export type OutputTuple = [timestamp: bigint, caller: string];
  export interface OutputObject {
    timestamp: bigint;
    caller: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HeirAddedEvent {
  export type InputTuple = [heir: AddressLike, allocationBps: BigNumberish];
  export type OutputTuple = [heir: string, allocationBps: bigint];
  export interface OutputObject {
    heir: string;
    allocationBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HeirRegisteredEvent {
  export type InputTuple = [heir: AddressLike, nullifierHash: BigNumberish];
  export type OutputTuple = [heir: string, nullifierHash: bigint];
  export interface OutputObject {
    heir: string;
    nullifierHash: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ThresholdUpdatedEvent {
  export type InputTuple = [
    oldThreshold: BigNumberish,
    newThreshold: BigNumberish
  ];
  export type OutputTuple = [oldThreshold: bigint, newThreshold: bigint];
  export interface OutputObject {
    oldThreshold: bigint;
    newThreshold: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LifeContract extends BaseContract {
  connect(runner?: ContractRunner | null): LifeContract;
  waitForDeployment(): Promise<this>;

  interface: LifeContractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addHeir: TypedContractMethod<
    [heir_: AddressLike, allocationBps_: BigNumberish],
    [void],
    "nonpayable"
  >;

  executeEstate: TypedContractMethod<[], [void], "nonpayable">;

  executed: TypedContractMethod<[], [boolean], "view">;

  getDaysElapsed: TypedContractMethod<[], [bigint], "view">;

  getHeir: TypedContractMethod<
    [index: BigNumberish],
    [
      [string, bigint, bigint, boolean] & {
        wallet: string;
        allocationBps: bigint;
        nullifierHash: bigint;
        isVerified: boolean;
      }
    ],
    "view"
  >;

  getHeirsCount: TypedContractMethod<[], [bigint], "view">;

  getStatus: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        lastPing_: bigint;
        threshold_: bigint;
        daysElapsed: bigint;
        thresholdDays: bigint;
        inactive: boolean;
      }
    ],
    "view"
  >;

  getThresholdDays: TypedContractMethod<[], [bigint], "view">;

  isHeir: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  isInactive: TypedContractMethod<[], [boolean], "view">;

  lastPing: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  ping: TypedContractMethod<[], [void], "nonpayable">;

  registerHeir: TypedContractMethod<
    [heir_: AddressLike, nullifierHash_: BigNumberish],
    [void],
    "nonpayable"
  >;

  setThreshold: TypedContractMethod<
    [thresholdDays: BigNumberish],
    [void],
    "nonpayable"
  >;

  threshold: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addHeir"
  ): TypedContractMethod<
    [heir_: AddressLike, allocationBps_: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executeEstate"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executed"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "getDaysElapsed"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getHeir"
  ): TypedContractMethod<
    [index: BigNumberish],
    [
      [string, bigint, bigint, boolean] & {
        wallet: string;
        allocationBps: bigint;
        nullifierHash: bigint;
        isVerified: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getHeirsCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getStatus"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        lastPing_: bigint;
        threshold_: bigint;
        daysElapsed: bigint;
        thresholdDays: bigint;
        inactive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getThresholdDays"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isHeir"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isInactive"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "lastPing"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ping"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registerHeir"
  ): TypedContractMethod<
    [heir_: AddressLike, nullifierHash_: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setThreshold"
  ): TypedContractMethod<[thresholdDays: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "threshold"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "EstateExecuted"
  ): TypedContractEvent<
    EstateExecutedEvent.InputTuple,
    EstateExecutedEvent.OutputTuple,
    EstateExecutedEvent.OutputObject
  >;
  getEvent(
    key: "HeartbeatReceived"
  ): TypedContractEvent<
    HeartbeatReceivedEvent.InputTuple,
    HeartbeatReceivedEvent.OutputTuple,
    HeartbeatReceivedEvent.OutputObject
  >;
  getEvent(
    key: "HeirAdded"
  ): TypedContractEvent<
    HeirAddedEvent.InputTuple,
    HeirAddedEvent.OutputTuple,
    HeirAddedEvent.OutputObject
  >;
  getEvent(
    key: "HeirRegistered"
  ): TypedContractEvent<
    HeirRegisteredEvent.InputTuple,
    HeirRegisteredEvent.OutputTuple,
    HeirRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ThresholdUpdated"
  ): TypedContractEvent<
    ThresholdUpdatedEvent.InputTuple,
    ThresholdUpdatedEvent.OutputTuple,
    ThresholdUpdatedEvent.OutputObject
  >;

  filters: {
    "EstateExecuted(uint256,uint256,uint256)": TypedContractEvent<
      EstateExecutedEvent.InputTuple,
      EstateExecutedEvent.OutputTuple,
      EstateExecutedEvent.OutputObject
    >;
    EstateExecuted: TypedContractEvent<
      EstateExecutedEvent.InputTuple,
      EstateExecutedEvent.OutputTuple,
      EstateExecutedEvent.OutputObject
    >;

    "HeartbeatReceived(uint256,address)": TypedContractEvent<
      HeartbeatReceivedEvent.InputTuple,
      HeartbeatReceivedEvent.OutputTuple,
      HeartbeatReceivedEvent.OutputObject
    >;
    HeartbeatReceived: TypedContractEvent<
      HeartbeatReceivedEvent.InputTuple,
      HeartbeatReceivedEvent.OutputTuple,
      HeartbeatReceivedEvent.OutputObject
    >;

    "HeirAdded(address,uint256)": TypedContractEvent<
      HeirAddedEvent.InputTuple,
      HeirAddedEvent.OutputTuple,
      HeirAddedEvent.OutputObject
    >;
    HeirAdded: TypedContractEvent<
      HeirAddedEvent.InputTuple,
      HeirAddedEvent.OutputTuple,
      HeirAddedEvent.OutputObject
    >;

    "HeirRegistered(address,uint256)": TypedContractEvent<
      HeirRegisteredEvent.InputTuple,
      HeirRegisteredEvent.OutputTuple,
      HeirRegisteredEvent.OutputObject
    >;
    HeirRegistered: TypedContractEvent<
      HeirRegisteredEvent.InputTuple,
      HeirRegisteredEvent.OutputTuple,
      HeirRegisteredEvent.OutputObject
    >;

    "ThresholdUpdated(uint256,uint256)": TypedContractEvent<
      ThresholdUpdatedEvent.InputTuple,
      ThresholdUpdatedEvent.OutputTuple,
      ThresholdUpdatedEvent.OutputObject
    >;
    ThresholdUpdated: TypedContractEvent<
      ThresholdUpdatedEvent.InputTuple,
      ThresholdUpdatedEvent.OutputTuple,
      ThresholdUpdatedEvent.OutputObject
    >;
  };
}
